gradle.beforeProject { project ->
  if (project.path == ':app') {
    project.pluginManager.withPlugin('com.android.application') {
      project.extensions.getByName('androidComponents').finalizeDsl { android ->
        android.defaultConfig.applicationId = 'dev.cedarflake.iftreleasecheck'
      }
    }
  }
}
